### ISSUE TITLE
Can pytorch 0.4.0 use this code? 

### ISSUE THREAD

**Issue by gaichengyuan** [luuuyi/CBAM.PyTorch#1]

**Comment by luuuyi** [comment]
@gaichengyuan When I complete this work, my bench is pytorch0.4.1, but I think pytorch0.4.0 can also work. You can try.

**Comment by tudou330121** [comment]
这个工程呀怎么运行起来？？？ 能给出具体的步骤吗  刚接触python 真的是一脸懵
