### ISSUE TITLE
Global Second Order Pooling

### ISSUE THREAD

**Issue by kayuksel** [luuuyi/CBAM.PyTorch#4]
I know you said that you do not have time but this is also interesting: https://arxiv.org/abs/1811.12006

**Comment by luuuyi** [comment]
@kayuksel Hi, thank you for your suggestion.

**Comment by kayuksel** [comment]
https://github.com/jiangtaoxie/fast-MPN-COV

**Comment by luuuyi** [comment]
@kayuksel got it.
